export const S4_CONFIG = {
  eventName: 'Hack with GDG S4', organizer: 'GDG On Campus KSRCE', venue: 'KSR College of Engineering', location: 'Namakkal, Tamil Nadu',
  eventStart: '2026-10-08T09:00:00+05:30', eventEnd: '2026-10-10T18:00:00+05:30', ideationDeadline: 'September 28, 2026', contactEmail: 'gdgksrce@gmail.com', instagramUrl: null, devfolioUrl: null,
  timeline: [{date:'SEPTEMBER 28, 2026',title:'IDEATION SUBMISSION DEADLINE'},{date:'OCTOBER 8, 2026',title:'36-HOUR HACKATHON BEGINS'},{date:'OCTOBER 9, 2026',title:'BUILD • MENTOR • COLLABORATE'},{date:'OCTOBER 10, 2026',title:'FINAL DEMO • JUDGING • CLOSING'}],
  archives: {s2: [], s3: []}, organizers: [], sponsors: [],
  faq: [
    ['WHO CAN PARTICIPATE?','Beginners and experienced builders are welcome.'],['WHAT IS THE TEAM SIZE?','1–4 members.'],['IS THE HACKATHON ONLINE OR OFFLINE?','The 36-hour hackathon is offline at KSR College of Engineering.'],['WHAT IS THE THEME?','Open Innovation.'],['WHEN IS THE IDEA SUBMISSION DEADLINE?','September 28, 2026.'],['DO I NEED A WORKING PROTOTYPE FOR ROUND 1?','A prototype is a plus, but selection focuses on the strength of the idea and problem-solving approach.'],['WHEN IS THE HACKATHON?','October 8–10, 2026.'],['WHAT ARE THE PRIZES?','Prize details will be announced soon.']]
};

document.addEventListener('DOMContentLoaded', () => {
  const header=document.getElementById('navbar'), toggle=document.getElementById('menuToggle'), mobile=document.getElementById('mobileNav');
  const setMenu=(open)=>{mobile?.classList.toggle('open',open);mobile?.setAttribute('aria-hidden',String(!open));toggle?.setAttribute('aria-expanded',String(open));toggle?.setAttribute('aria-label',open?'Close navigation':'Open navigation')};
  toggle?.addEventListener('click',()=>setMenu(!mobile?.classList.contains('open'))); mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false))); document.addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
  const links=[...document.querySelectorAll('.desktop-nav a[data-section],.mobile-nav a[data-section]')]; const sections=[...document.querySelectorAll('main section[id]')];
  const setActive=id=>links.forEach(a=>{const active=a.dataset.section===id;a.classList.toggle('active',active);a.setAttribute('aria-current',active?'true':'false')});
  const observer=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive(v.target.id)},{rootMargin:'-25% 0px -60% 0px',threshold:[.1,.3,.6]});sections.forEach(s=>observer.observe(s));
  const headerUpdate=()=>header?.classList.toggle('scrolled',scrollY>20);addEventListener('scroll',headerUpdate,{passive:true});headerUpdate();
  document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(a.matches('[data-devfolio-cta]')&&!S4_CONFIG.devfolioUrl){e.preventDefault();alert('Devfolio applications will open soon. The official link will be shared here.');return}const target=document.querySelector(href);if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'})}}));
  document.querySelectorAll('[data-devfolio-cta]').forEach(a=>{if(S4_CONFIG.devfolioUrl)a.href=S4_CONFIG.devfolioUrl});document.querySelectorAll('[data-placeholder-action]').forEach(b=>b.addEventListener('click',()=>alert('Directions will be available when the official venue map is published.')));
  const ids=['days','hours','minutes','seconds'];const labels=[...document.querySelectorAll('[id="countdown-label"]')];const update=()=>{const now=Date.now(),start=+new Date(S4_CONFIG.eventStart),end=+new Date(S4_CONFIG.eventEnd),before=now<start,during=now>=start&&now<end,left=Math.max(0,(before?start:end)-now);labels.forEach(l=>l.textContent=before?'THE BUILD BEGINS IN':during?'HACK WITH GDG S4 IS LIVE':'HACK WITH GDG S4 — THANK YOU, BUILDERS');[Math.floor(left/864e5),Math.floor(left/36e5)%24,Math.floor(left/6e4)%60,Math.floor(left/1e3)%60].forEach((v,i)=>document.querySelectorAll(`[data-countdown-value="${ids[i]}"]`).forEach(el=>{const next=String(v).padStart(2,'0');if(el.textContent!==next){el.classList.remove('countdown-pop');void el.offsetWidth;el.classList.add('countdown-pop')}el.textContent=next}))};update();setInterval(update,1000);
  const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>revealObserver.observe(e));
  const tl=document.querySelector('.timeline-list');if(tl){tl.innerHTML='';S4_CONFIG.timeline.forEach(({date,title},i)=>{const li=document.createElement('li');li.className='timeline-item';li.innerHTML=`<div class="timeline-marker">${String(i+1).padStart(2,'0')}</div><div class="timeline-date"><time>${date}</time><h3>${title}</h3></div>`;tl.append(li)});}
  const list=document.getElementById('faqList');if(list) S4_CONFIG.faq.forEach(([q,a],i)=>{const item=document.createElement('div');item.className='faq-item';item.innerHTML=`<button class="faq-question" type="button" aria-expanded="false" aria-controls="faq-answer-${i}"><span>${q}</span><span aria-hidden="true">＋</span></button><div class="faq-answer" id="faq-answer-${i}" role="region" aria-labelledby="faq-question-${i}" hidden><div><p>${a}</p></div></div>`;const button=item.querySelector('button'),answer=item.querySelector('.faq-answer');button.id=`faq-question-${i}`;button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));answer.hidden=open;answer.classList.toggle('open',!open)});list.append(item)});
});
if(typeof window!=='undefined')window.S4_CONFIG=S4_CONFIG;if(typeof module!=='undefined')module.exports={S4_CONFIG};
